services:
  web:
    build:
      context: .
      target: development     
    volumes:
      - .:/app                
    ports:
      - "8000:8000"

  tailwind:
    build:
      context: .
      target: development
    volumes:
      - .:/app                                    # même volume que web
    working_dir: /app/src
    command: python manage.py tailwind start      # watch mode
    depends_on:
      - web
    restart: unless-stopped
    tty: true        # ← garde le processus actif
    stdin_open: true # ← équivalent de docker run -it