# Generated by Django 5.2 on 2026-05-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=50)),
                ('explication', models.TextField(blank=True)),
                ('contenu', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/images/')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='home/files/')),
            ],
            options={
                'verbose_name': 'Contenu par défaut',
            },
        ),
        migrations.CreateModel(
            name='Libelles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=50)),
                ('explication', models.TextField(blank=True)),
                ('contenu', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/images/')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='home/files/')),
                ('lien', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'libellé',
            },
        ),
    ]
